services:
  back_for_motor:
    container_name: back_for_motor
    build: 
      context: .
      dockerfile: back.dockerfile
    volumes:
      - ./api:/api
      - ./alembic:/alembic
      - ./backups:/backups
      - ./uploads:/app/uploads
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database_postgres_for_motor
    environment:
      - DATABASE_URL=postgresql+asyncpg://root:root@database_postgres_for_motor:5432/db_motor
    restart: always
  database_postgres_for_motor:  
    container_name: database_for_motor 
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: db_motor 
    volumes:
      - pg_data_data:/var/lib/postgresql/data/data

volumes:
  pg_data_data:
