"""initial migration

Revision ID: 304a8ad9faa1
Revises: 
Create Date: 2026-06-14 14:15:56.631470
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '304a8ad9faa1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('site_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('site_type', sa.Enum('WAREHOUSE', 'SHOWROOM', 'ASSEMBLY_PLANT', 'JOINT', name='sitetype'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('RECEIVER', 'ASSEMBLER', 'SALES_REP', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('assigned_site_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['assigned_site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('deliveries',
    sa.Column('delivery_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_no', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=True),
    sa.Column('received_at_site_id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['received_at_site_id'], ['sites.site_id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('delivery_id'),
    sa.UniqueConstraint('delivery_no')
    )
    op.create_table('invoices',
    sa.Column('invoice_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'FINANCING', 'BANK_TRANSFER', name='paymentmethod'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sold_by', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.ForeignKeyConstraint(['sold_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('motors',
    sa.Column('motor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'IN_PROGRESS', 'READY_FOR_SALE', 'SOLD', 'DEFECTIVE', name='motorstatus'), nullable=False),
    sa.Column('current_site_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('assembly_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assembled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assembled_by', sa.Integer(), nullable=True),
    sa.Column('quality_check_passed', sa.Boolean(), nullable=True),
    sa.Column('defect_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assembled_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['current_site_id'], ['sites.site_id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.delivery_id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('motor_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('invoice_motors',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('motor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.motor_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('invoice_id', 'motor_id'),
    sa.UniqueConstraint('motor_id')
    )
    op.create_table('site_transfer_history',
    sa.Column('transfer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('motor_id', sa.Integer(), nullable=False),
    sa.Column('from_site_id', sa.Integer(), nullable=True),
    sa.Column('to_site_id', sa.Integer(), nullable=True),
    sa.Column('transferred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transferred_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('RECEIVED', 'ASSEMBLY_COMPLETE', 'STOCK_MOVE', 'RETURN_DEFECTIVE', 'SALE_TRANSFER', name='transferreason'), nullable=False),
    sa.ForeignKeyConstraint(['from_site_id'], ['sites.site_id'], ),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.motor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_site_id'], ['sites.site_id'], ),
    sa.ForeignKeyConstraint(['transferred_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_transfer_history')
    op.drop_table('invoice_motors')
    op.drop_table('motors')
    op.drop_table('invoices')
    op.drop_table('deliveries')
    op.drop_table('users')
    op.drop_table('sites')
    # ### end Alembic commands ###
