"""add customer identification fields to invoices

Revision ID: a1b2c3d4e5f6
Revises: 304a8ad9faa1
Create Date: 2026-06-17 15:00:00.000000+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '304a8ad9faa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    op.execute("CREATE TYPE invoicestatus AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'VOIDED')")
    op.add_column('invoices', sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'VOIDED', name='invoicestatus'), nullable=True, server_default='PENDING_APPROVAL'))
    op.add_column('invoices', sa.Column('payment_proof_path', sa.String(length=500), nullable=True))
    op.add_column('invoices', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('customer_id_number', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('customer_id_type', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('customer_id_issue_date', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('customer_id_expiry_date', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('customer_id_authority', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('customer_alt_phone', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('customer_email', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('customer_region', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('customer_city', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('customer_sub_city', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('customer_woreda', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('customer_house_number', sa.String(length=50), nullable=True))
    
    # Alter customer_name from length 100 to 200
    op.alter_column('invoices', 'customer_name', type_=sa.String(length=200))
    
    # Add foreign key for approved_by
    op.create_foreign_key('fk_invoices_approved_by', 'invoices', 'users', ['approved_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invoices_approved_by', 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'customer_house_number')
    op.drop_column('invoices', 'customer_woreda')
    op.drop_column('invoices', 'customer_sub_city')
    op.drop_column('invoices', 'customer_city')
    op.drop_column('invoices', 'customer_region')
    op.drop_column('invoices', 'customer_email')
    op.drop_column('invoices', 'customer_alt_phone')
    op.drop_column('invoices', 'customer_id_authority')
    op.drop_column('invoices', 'customer_id_expiry_date')
    op.drop_column('invoices', 'customer_id_issue_date')
    op.drop_column('invoices', 'customer_id_type')
    op.drop_column('invoices', 'customer_id_number')
    op.drop_column('invoices', 'rejection_reason')
    op.drop_column('invoices', 'approved_by')
    op.drop_column('invoices', 'approved_at')
    op.drop_column('invoices', 'payment_proof_path')
    op.drop_column('invoices', 'status')
    op.execute("DROP TYPE invoicestatus")
    op.alter_column('invoices', 'customer_name', type_=sa.String(length=100))
    # ### end Alembic commands ###